### ISSUE TITLE
WakePeriodically.ino - Where to insert the line : SleepyPi.enablePiPower(true)

### ISSUE THREAD

**Issue by captainigloo** [SpellFoundry/SleepyPi2#1]
After several non-functional tests impossible to operate this [sketch](https://github.com/SpellFoundry/SleepyPi2/blob/master/examples/WakePeriodically/WakePeriodically.ino)
//     SleepyPi.enablePiPower(true);  
// after arduino wakeup. 

Tests done with input of micro USB 5v or 5-30v Sleepy PI2. In which position should the jumper hardware or software be placed?

**Comment by SpellFoundry** [comment]
Hi I've added an example: WakePiPeriodically which hopefully point you in the right direction. Also take a look at the new WakeUpPiPeridicallyOnAlarm which may also help.

**Comment by captainigloo** [comment]
Hi,
Thanks !

**Comment by captainigloo** [comment]
Great ! Perfect.
