### ISSUE TITLE
New release with compatibility with Time 1.6.1

### ISSUE THREAD

**Issue by anarkiwi** [SpellFoundry/SleepyPi2#20]
Hello,

Yesterday, Time 1.6.1 was released which is incompatible with Sleepy Pi 2 because of Time.h versus TimeLib.h.

There is already an unreleased change that fixes the problem (https://github.com/SpellFoundry/SleepyPi2/compare/V1.0.0...master).

Would it be possible to get a new release, please?

**Comment by SpellFoundry** [comment]
Hopefully, that's done now. As you pointed out, the commit was done but not reflected in the release, doh!

**Comment by anarkiwi** [comment]
Thanks. Looks like the Arduino IDE still doesn't see the new library - I guess there's some kinda index latency mumble process there.

**Comment by anarkiwi** [comment]
Sent a PR to update library properties.
