### ISSUE TITLE
Defined twice

### ISSUE THREAD

**Issue by jensjakob** [SpellFoundry/SleepyPi2#5]
kONBUTTONTIME_MS is defined twice in SleepyPi2.h, line 21 and 22

This gives a warning and note in Arduino IDE.

https://github.com/SpellFoundry/SleepyPi2/blob/def9d3828ee1a777727d350588887a929b8b77a6/SleepyPi2.h#L22

**Comment by SpellFoundry** [comment]
Thanks for that, changed
